plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.10'
}

group = 'com.jas.agent'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.ow2.asm:asm-commons:9.9.1'
}

jar {
    archiveBaseName = 'agent'

    manifest {
        attributes 'Premain-Class': 'com.burpsuite.Main'
        attributes 'Agent-Class': 'com.burpsuite.Main'
        attributes 'Can-Redefine-Classes': true
        attributes 'Can-Retransform-Classes': true
        attributes 'Can-Set-Native-Method-Prefix': true
    }

    finalizedBy(shadowJar)
}